name: 'Build Deploy GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: .

    - name: Uncompress Artifact
      run: |
        tar -xzvf dist.tar.gz
      shell: bash

    - name: Review Artifact
      run: ls -laR .
      shell: bash

    - name: Deploy Project
      uses: cevixe/deploy@v1
